### ISSUE TITLE
board type

### ISSUE THREAD

**Issue by axljackass** [MUSTARDTIGERFPV/PPM2CRSF#1]
thank you for sharing.

very long time im waiting for this and finally i can reuse back my old Turnigy 9X transmitter.

Any interest in using smaller boards like ESP-01?
Can easily fit inside a DIY ELRS TX.

Thanks

(",

**Comment by MUSTARDTIGERFPV** [comment]
Currently, PPM2CRSF works only on ESP32 boards. That said, there are plans for ELRS to natively support PPM in when future versions are released, so PPM2CRSF might not be necessary soon. :)

**Comment by yonmudi** [comment]
Is there an article or video on how to make it?

**Comment by MUSTARDTIGERFPV** [comment]
> Is there an article or video on how to make it?
ExpressLRS now natively supports PPM inputs on ESP32 transmitters. It's recommended to use that.
